### ISSUE TITLE
平台监控无法获取数据

### ISSUE THREAD

**Issue by NaNShaner** [dianping/camel#23]
![chart](https://user-images.githubusercontent.com/20882547/50161237-2c5d8100-0316-11e9-955a-787967e68127.png)
并且admin的日志中抛出如下日志，请问是否部署上有什么问题？
java.lang.RuntimeException: statuscode has no data:all 
	at com.dianping.phoenix.lb.action.StatusMonitorAction.showDashboard(StatusMonitorAction.java:311) [classes/:na]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_171]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_171]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_171]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_171]
	at com.opensymphony.xwork2.DefaultActionInvocation.invokeAction(DefaultActionInvocation.java:450) [xwork-core-2.3.16.2.1.jar:2.3.16.2.1]
	at com.opensymphony.xwork2.DefaultActionInvocation.invokeActionOnly(DefaultActionInvocation.java:289) [xwork-core-2.3.16.2.1.jar:2.3.16.2.1]
	at com.opensymphony.xwork2.DefaultActionInvocation.invoke(DefaultActionInvocation.java:252) [xwork-core-2.3.16.2.1.jar:2.3.16.2.1]
	at com.dianping.phoenix.lb.action.interceptor.RecordInterceptor.intercept(RecordInterceptor.java:72) [classes/:na]
	at com.opensymphony.xwork2.DefaultActionInvocation.invoke(DefaultActionInvocation.java:246) [xwork-core-2.3.16.2.1.jar:2.3.16.2.1]
	at org.apache.struts2.interceptor.DeprecationInterceptor.intercept(DeprecationInterceptor.java:41) [struts2-core-2.3.16.2.jar:2.3.16.2]
	at com.opensymphony.xwork2.DefaultActionInvocation.invoke(DefaultActionInvocation.java:246) [xwork-core-2.3.16.2.1.jar:2.3.16.2.1]
	at org.apache.struts2.interceptor.debugging.DebuggingInterceptor.intercept(DebuggingInterceptor.java:256) [struts2-core-2.3.16.2.jar:2.3.16.2]
	at com.opensymphony.xwork2.DefaultActionInvocation.invoke(DefaultActionInvocation.java:246) [xwork-core-2.3.16.2.1.jar:2.3.16.2.1]
	at com.opensymphony.xwork2.interceptor.DefaultWorkflowInterceptor.doIntercept(DefaultWorkflowInterceptor.java:167) [xwork-core-2.3.16.2.1.jar:2.3.16.2.1]

**Comment by leonindy** [comment]
这个监控，是调用Nginx接口，获取Nginx状态数据。

你手工调用下Nginx接口看看有没有数据，是否是防火墙等原因
