### ISSUE TITLE
创建发布任务时抛异常 -- "Column 'creation_date' cannot be null"

### ISSUE THREAD

**Issue by tuxknight** [dianping/camel#4]
下面是管理端的日志：

```
admin_1  | 2016-09-19 16:08:34.036 [ERROR] [] [http-bio-8080-exec-1] com.dianping.phoenix.lb.action.DeployAction -
admin_1  | ### Error updating database.  Cause: com.mysql.jdbc.exceptions.jdbc4.MySQLIntegrityConstraintViolationException: Column 'creation_date' cannot be null
admin_1  | ### The error may involve com.dianping.phoenix.lb.deploy.dao.DeployTaskMapper.insert-Inline
admin_1  | ### The error occurred while setting parameters
admin_1  | ### Cause: com.mysql.jdbc.exceptions.jdbc4.MySQLIntegrityConstraintViolationException: Column 'creation_date' cannot be null
admin_1  | ; SQL []; Column 'creation_date' cannot be null; nested exception is com.mysql.jdbc.exceptions.jdbc4.MySQLIntegrityConstraintViolationException: Column 'creation_date' cannot be null
admin_1  | org.springframework.dao.DataIntegrityViolationException:
admin_1  | ### Error updating database.  Cause: com.mysql.jdbc.exceptions.jdbc4.MySQLIntegrityConstraintViolationException: Column 'creation_date' cannot be null
admin_1  | ### The error may involve com.dianping.phoenix.lb.deploy.dao.DeployTaskMapper.insert-Inline
admin_1  | ### The error occurred while setting parameters
admin_1  | ### Cause: com.mysql.jdbc.exceptions.jdbc4.MySQLIntegrityConstraintViolationException: Column 'creation_date' cannot be null
admin_1  | ; SQL []; Column 'creation_date' cannot be null; nested exception is com.mysql.jdbc.exceptions.jdbc4.MySQLIntegrityConstraintViolationException: Column 'creation_date' cannot be null
admin_1  |  at org.springframework.jdbc.support.SQLExceptionSubclassTranslator.doTranslate(SQLExceptionSubclassTranslator.java:86) ~[spring-jdbc-3.2.10.RELEASE.jar:3.2.10.RELEASE]
admin_1  |  at org.springframework.jdbc.support.AbstractFallbackSQLExceptionTranslator.translate(AbstractFallbackSQLExceptionTranslator.java:72) ~[spring-jdbc-3.2.10.RELEASE.jar:3.2.10.RELEASE]
admin_1  |  at org.springframework.jdbc.support.AbstractFallbackSQLExceptionTranslator.translate(AbstractFallbackSQLExceptionTranslator.java:80) ~[spring-jdbc-3.2.10.RELEASE.jar:3.2.10.RELEASE]
admin_1  |  at org.mybatis.spring.MyBatisExceptionTranslator.translateExceptionIfPossible(MyBatisExceptionTranslator.java:71) ~[mybatis-spring-1.0.1.jar:1.0.1]
admin_1  |  at org.mybatis.spring.SqlSessionTemplate$SqlSessionInterceptor.invoke(SqlSessionTemplate.java:346) ~[mybatis-spring-1.0.1.jar:1.0.1]
admin_1  |  at com.sun.proxy.$Proxy12.insert(Unknown Source) ~[na:na]
admin_1  |  at org.mybatis.spring.SqlSessionTemplate.insert(SqlSessionTemplate.java:231) ~[mybatis-spring-1.0.1.jar:1.0.1]
admin_1  |  at org.apache.ibatis.binding.MapperMethod.execute(MapperMethod.java:59) ~[mybatis-3.0.6.jar:3.0.6]
admin_1  |  at org.apache.ibatis.binding.MapperProxy.invoke(MapperProxy.java:25) ~[mybatis-3.0.6.jar:3.0.6]
admin_1  |  at com.sun.proxy.$Proxy18.insert(Unknown Source) ~[na:na]
admin_1  |  at com.dianping.phoenix.lb.deploy.service.impl.DeployTaskServiceImpl.addTask(DeployTaskServiceImpl.java:194) ~[DeployTaskServiceImpl.class:na]
admin_1  |  at com.dianping.phoenix.lb.action.DeployAction.addDeployTask(DeployAction.java:107) ~[DeployAction.class:na]
admin_1  |  at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.7.0_71]
admin_1  |  at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57) ~[na:1.7.0_71]
admin_1  |  at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.7.0_71]
admin_1  |  at java.lang.reflect.Method.invoke(Method.java:606) ~[na:1.7.0_71]
admin_1  |  at com.opensymphony.xwork2.DefaultActionInvocation.invokeAction(DefaultActionInvocation.java:450) [xwork-core-2.3.16.2.1.jar:2.3.16.2.1]
admin_1  |  at com.opensymphony.xwork2.DefaultActionInvocation.invokeActionOnly(DefaultActionInvocation.java:289) [xwork-core-2.3.16.2.1.jar:2.3.16.2.1]
admin_1  |  at com.opensymphony.xwork2.DefaultActionInvocation.invoke(DefaultActionInvocation.java:252) [xwork-core-2.3.16.2.1.jar:2.3.16.2.1]
admin_1  |  at com.dianping.phoenix.lb.action.interceptor.RecordInterceptor.intercept(RecordInterceptor.java:72) [RecordInterceptor.class:na]
admin_1  |  at com.opensymphony.xwork2.DefaultActionInvocation.invoke(DefaultActionInvocation.java:246) [xwork-core-2.3.16.2.1.jar:2.3.16.2.1]
admin_1  |  at org.apache.struts2.interceptor.DeprecationInterceptor.intercept(DeprecationInterceptor.java:41) [struts2-core-2.3.16.2.jar:2.3.16.2]
admin_1  |  at com.opensymphony.xwork2.DefaultActionInvocation.invoke(DefaultActionInvocation.java:246) [xwork-core-2.3.16.2.1.jar:2.3.16.2.1]
admin_1  |  at org.apache.struts2.interceptor.debugging.DebuggingInterceptor.intercept(DebuggingInterceptor.java:256) [struts2-core-2.3.16.2.jar:2.3.16.2]
admin_1  |  at com.opensymphony.xwork2.DefaultActionInvocation.invoke(DefaultActionInvocation.java:246) [xwork-core-2.3.16.2.1.jar:2.3.16.2.1]
admin_1  |  at com.opensymphony.xwork2.interceptor.DefaultWorkflowInterceptor.doIntercept(DefaultWorkflowInterceptor.java:167) [xwork-core-2.3.16.2.1.jar:2.3.16.2.1]
admin_1  |  at com.opensymphony.xwork2.interceptor.MethodFilterInterceptor.intercept(MethodFilterInterceptor.java:98) [xwork-core-2.3.16.2.1.jar:2.3.16.2.1]
admin_1  |  at com.opensymphony.xwork2.DefaultActionInvocation.invoke(DefaultActionInvocation.java:246) [xwork-core-2.3.16.2.1.jar:2.3.16.2.1]
admin_1  |  at com.opensymphony.xwork2.validator.ValidationInterceptor.doIntercept(ValidationInterceptor.java:265) [xwork-core-2.3.16.2.1.jar:2.3.16.2.1]
admin_1  |  at org.apache.struts2.interceptor.validation.AnnotationValidationInterceptor.doIntercept(AnnotationValidationInterceptor.java:68) [struts2-core-2.3.16.2.jar:2.3.16.2]
admin_1  |  at com.opensymphony.xwork2.interceptor.MethodFilterInterceptor.intercept(MethodFilterInterceptor.java:98) [xwork-core-2.3.16.2.1.jar:2.3.16.2.1]
admin_1  |  at com.opensymphony.xwork2.DefaultActionInvocation.invoke(DefaultActionInvocation.java:246) [xwork-core-2.3.16.2.1.jar:2.3.16.2.1]
admin_1  |  at com.opensymphony.xwork2.interceptor.ConversionErrorInterceptor.intercept(ConversionErrorInterceptor.java:138) [xwork-core-2.3.16.2.1.jar:2.3.16.2.1]
admin_1  |  at com.opensymphony.xwork2.DefaultActionInvocation.invoke(DefaultActionInvocation.java:246) [xwork-core-2.3.16.2.1.jar:2.3.16.2.1]
admin_1  |  at com.opensymphony.xwork2.interceptor.ParametersInterceptor.doIntercept(ParametersInterceptor.java:254) [xwork-core-2.3.16.2.1.jar:2.3.16.2.1]
admin_1  |  at com.opensymphony.xwork2.interceptor.MethodFilterInterceptor.intercept(MethodFilterInterceptor.java:98) [xwork-core-2.3.16.2.1.jar:2.3.16.2.1]
admin_1  |  at com.opensymphony.xwork2.DefaultActionInvocation.invoke(DefaultActionInvocation.java:246) [xwork-core-2.3.16.2.1.jar:2.3.16.2.1]
admin_1  |  at com.opensymphony.xwork2.interceptor.ParametersInterceptor.doIntercept(ParametersInterceptor.java:254) [xwork-core-2.3.16.2.1.jar:2.3.16.2.1]
admin_1  |  at com.opensymphony.xwork2.interceptor.MethodFilterInterceptor.intercept(MethodFilterInterceptor.java:98) [xwork-core-2.3.16.2.1.jar:2.3.16.2.1]
admin_1  |  at com.opensymphony.xwork2.DefaultActionInvocation.invoke(DefaultActionInvocation.java:246) [xwork-core-2.3.16.2.1.jar:2.3.16.2.1]
admin_1  |  at com.opensymphony.xwork2.interceptor.StaticParametersInterceptor.intercept(StaticParametersInterceptor.java:191) [xwork-core-2.3.16.2.1.jar:2.3.16.2.1]
admin_1  |  at com.opensymphony.xwork2.DefaultActionInvocation.invoke(DefaultActionInvocation.java:246) [xwork-core-2.3.16.2.1.jar:2.3.16.2.1]
admin_1  |  at org.apache.struts2.interceptor.MultiselectInterceptor.intercept(MultiselectInterceptor.java:73) [struts2-core-2.3.16.2.jar:2.3.16.2]
admin_1  |  at com.opensymphony.xwork2.DefaultActionInvocation.invoke(DefaultActionInvocation.java:246) [xwork-core-2.3.16.2.1.jar:2.3.16.2.1]
admin_1  |  at org.apache.struts2.interceptor.CheckboxInterceptor.intercept(CheckboxInterceptor.java:91) [struts2-core-2.3.16.2.jar:2.3.16.2]
admin_1  |  at com.opensymphony.xwork2.DefaultActionInvocation.invoke(DefaultActionInvocation.java:246) [xwork-core-2.3.16.2.1.jar:2.3.16.2.1]
admin_1  |  at org.apache.struts2.interceptor.FileUploadInterceptor.intercept(FileUploadInterceptor.java:252) [struts2-core-2.3.16.2.jar:2.3.16.2]
admin_1  |  at com.opensymphony.xwork2.DefaultActionInvocation.invoke(DefaultActionInvocation.java:246) [xwork-core-2.3.16.2.1.jar:2.3.16.2.1]
admin_1  |  at com.opensymphony.xwork2.interceptor.ModelDrivenInterceptor.intercept(ModelDrivenInterceptor.java:100) [xwork-core-2.3.16.2.1.jar:2.3.16.2.1]
admin_1  |  at com.opensymphony.xwork2.DefaultActionInvocation.invoke(DefaultActionInvocation.java:246) [xwork-core-2.3.16.2.1.jar:2.3.16.2.1]
admin_1  |  at com.opensymphony.xwork2.interceptor.ScopedModelDrivenInterceptor.intercept(ScopedModelDrivenInterceptor.java:141) [xwork-core-2.3.16.2.1.jar:2.3.16.2.1]
admin_1  |  at com.opensymphony.xwork2.DefaultActionInvocation.invoke(DefaultActionInvocation.java:246) [xwork-core-2.3.16.2.1.jar:2.3.16.2.1]
admin_1  |  at com.opensymphony.xwork2.interceptor.ChainingInterceptor.intercept(ChainingInterceptor.java:145) [xwork-core-2.3.16.2.1.jar:2.3.16.2.1]
admin_1  |  at com.opensymphony.xwork2.DefaultActionInvocation.invoke(DefaultActionInvocation.java:246) [xwork-core-2.3.16.2.1.jar:2.3.16.2.1]
admin_1  |  at com.opensymphony.xwork2.interceptor.PrepareInterceptor.doIntercept(PrepareInterceptor.java:171) [xwork-core-2.3.16.2.1.jar:2.3.16.2.1]
admin_1  |  at com.opensymphony.xwork2.interceptor.MethodFilterInterceptor.intercept(MethodFilterInterceptor.java:98) [xwork-core-2.3.16.2.1.jar:2.3.16.2.1]
admin_1  |  at com.opensymphony.xwork2.DefaultActionInvocation.invoke(DefaultActionInvocation.java:246) [xwork-core-2.3.16.2.1.jar:2.3.16.2.1]
admin_1  |  at com.opensymphony.xwork2.interceptor.I18nInterceptor.intercept(I18nInterceptor.java:139) [xwork-core-2.3.16.2.1.jar:2.3.16.2.1]
admin_1  |  at com.opensymphony.xwork2.DefaultActionInvocation.invoke(DefaultActionInvocation.java:246) [xwork-core-2.3.16.2.1.jar:2.3.16.2.1]
admin_1  |  at org.apache.struts2.interceptor.ServletConfigInterceptor.intercept(ServletConfigInterceptor.java:164) [struts2-core-2.3.16.2.jar:2.3.16.2]
admin_1  |  at com.opensymphony.xwork2.DefaultActionInvocation.invoke(DefaultActionInvocation.java:246) [xwork-core-2.3.16.2.1.jar:2.3.16.2.1]
admin_1  |  at com.opensymphony.xwork2.interceptor.AliasInterceptor.intercept(AliasInterceptor.java:193) [xwork-core-2.3.16.2.1.jar:2.3.16.2.1]
admin_1  |  at com.opensymphony.xwork2.DefaultActionInvocation.invoke(DefaultActionInvocation.java:246) [xwork-core-2.3.16.2.1.jar:2.3.16.2.1]
admin_1  |  at com.opensymphony.xwork2.interceptor.ExceptionMappingInterceptor.intercept(ExceptionMappingInterceptor.java:189) [xwork-core-2.3.16.2.1.jar:2.3.16.2.1]
admin_1  |  at com.opensymphony.xwork2.DefaultActionInvocation.invoke(DefaultActionInvocation.java:246) [xwork-core-2.3.16.2.1.jar:2.3.16.2.1]
admin_1  |  at org.apache.struts2.impl.StrutsActionProxy.execute(StrutsActionProxy.java:54) [struts2-core-2.3.16.2.jar:2.3.16.2]
admin_1  |  at org.apache.struts2.dispatcher.Dispatcher.serviceAction(Dispatcher.java:562) [struts2-core-2.3.16.2.jar:2.3.16.2]
admin_1  |  at org.apache.struts2.dispatcher.ng.ExecuteOperations.executeAction(ExecuteOperations.java:77) [struts2-core-2.3.16.2.jar:2.3.16.2]
admin_1  |  at org.apache.struts2.dispatcher.ng.filter.StrutsPrepareAndExecuteFilter.doFilter(StrutsPrepareAndExecuteFilter.java:99) [struts2-core-2.3.16.2.jar:2.3.16.2]
admin_1  |  at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241) [catalina.jar:7.0.62]
admin_1  |  at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208) [catalina.jar:7.0.62]
admin_1  |  at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:88) [spring-web-3.0.5.RELEASE.jar:3.0.5.RELEASE]
admin_1  |  at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:76) [spring-web-3.0.5.RELEASE.jar:3.0.5.RELEASE]
admin_1  |  at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241) [catalina.jar:7.0.62]
admin_1  |  at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208) [catalina.jar:7.0.62]
admin_1  |  at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:220) [catalina.jar:7.0.62]
admin_1  |  at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:122) [catalina.jar:7.0.62]
admin_1  |  at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:505) [catalina.jar:7.0.62]
admin_1  |  at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:170) [catalina.jar:7.0.62]
admin_1  |  at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:103) [catalina.jar:7.0.62]
admin_1  |  at org.apache.catalina.valves.AccessLogValve.invoke(AccessLogValve.java:957) [catalina.jar:7.0.62]
admin_1  |  at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:116) [catalina.jar:7.0.62]
admin_1  |  at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:423) [catalina.jar:7.0.62]
admin_1  |  at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1079) [tomcat-coyote.jar:7.0.62]
admin_1  |  at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:620) [tomcat-coyote.jar:7.0.62]
admin_1  |  at org.apache.tomcat.util.net.JIoEndpoint$SocketProcessor.run(JIoEndpoint.java:318) [tomcat-coyote.jar:7.0.62]
admin_1  |  at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145) [na:1.7.0_71]
admin_1  |  at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615) [na:1.7.0_71]
admin_1  |  at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61) [tomcat-coyote.jar:7.0.62]
admin_1  |  at java.lang.Thread.run(Thread.java:745) [na:1.7.0_71]
admin_1  | Caused by: com.mysql.jdbc.exceptions.jdbc4.MySQLIntegrityConstraintViolationException: Column 'creation_date' cannot be null
admin_1  |  at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[na:1.7.0_71]
admin_1  |  at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:57) ~[na:1.7.0_71]
admin_1  |  at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[na:1.7.0_71]
admin_1  |  at java.lang.reflect.Constructor.newInstance(Constructor.java:526) ~[na:1.7.0_71]
admin_1  |  at com.mysql.jdbc.Util.handleNewInstance(Util.java:411) ~[mysql-connector-java-5.1.20.jar:na]
admin_1  |  at com.mysql.jdbc.Util.getInstance(Util.java:386) ~[mysql-connector-java-5.1.20.jar:na]
admin_1  |  at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:1039) ~[mysql-connector-java-5.1.20.jar:na]
admin_1  |  at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:4096) ~[mysql-connector-java-5.1.20.jar:na]
admin_1  |  at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:4028) ~[mysql-connector-java-5.1.20.jar:na]
admin_1  |  at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2490) ~[mysql-connector-java-5.1.20.jar:na]
admin_1  |  at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2651) ~[mysql-connector-java-5.1.20.jar:na]
admin_1  |  at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2683) ~[mysql-connector-java-5.1.20.jar:na]
admin_1  |  at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:2144) ~[mysql-connector-java-5.1.20.jar:na]
admin_1  |  at com.mysql.jdbc.PreparedStatement.execute(PreparedStatement.java:1379) ~[mysql-connector-java-5.1.20.jar:na]
admin_1  |  at com.mchange.v2.c3p0.impl.NewProxyPreparedStatement.execute(NewProxyPreparedStatement.java:989) ~[c3p0-0.9.1.2.jar:0.9.1.2]
admin_1  |  at org.apache.ibatis.executor.statement.PreparedStatementHandler.update(PreparedStatementHandler.java:22) ~[mybatis-3.0.6.jar:3.0.6]
admin_1  |  at org.apache.ibatis.executor.statement.RoutingStatementHandler.update(RoutingStatementHandler.java:51) ~[mybatis-3.0.6.jar:3.0.6]
admin_1  |  at org.apache.ibatis.executor.SimpleExecutor.doUpdate(SimpleExecutor.java:29) ~[mybatis-3.0.6.jar:3.0.6]
admin_1  |  at org.apache.ibatis.executor.BaseExecutor.update(BaseExecutor.java:88) ~[mybatis-3.0.6.jar:3.0.6]
admin_1  |  at org.apache.ibatis.executor.CachingExecutor.update(CachingExecutor.java:43) ~[mybatis-3.0.6.jar:3.0.6]
admin_1  |  at org.apache.ibatis.session.defaults.DefaultSqlSession.update(DefaultSqlSession.java:122) ~[mybatis-3.0.6.jar:3.0.6]
admin_1  |  at org.apache.ibatis.session.defaults.DefaultSqlSession.insert(DefaultSqlSession.java:111) ~[mybatis-3.0.6.jar:3.0.6]
admin_1  |  at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.7.0_71]
admin_1  |  at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57) ~[na:1.7.0_71]
admin_1  |  at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.7.0_71]
admin_1  |  at java.lang.reflect.Method.invoke(Method.java:606) ~[na:1.7.0_71]
admin_1  |  at org.mybatis.spring.SqlSessionTemplate$SqlSessionInterceptor.invoke(SqlSessionTemplate.java:338) ~[mybatis-spring-1.0.1.jar:1.0.1]
admin_1  |  ... 85 common frames omitted
```

**Comment by QLeelulu** [comment]
```
alter table deploy_task CHANGE `creation_date` `creation_date` timestamp default CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
```

修改下MySQL的表结构可以了
